### ISSUE TITLE
Front end shitsz

### ISSUE THREAD

**Issue by IllusionBox** [IllusionBox/LTGallery#2]
@maleenj 
Make all the black bars slightly transparent :)
The categories pages have to be brushed up
We need a better font

**Comment by janithajc** [comment]
Black bars transparented, font please suggest @maleenj my tastes are very bad.
Will work on Categories page, but will actually get to it with the back end @dhammika-marasinghe we need to start back end

**Comment by IllusionBox** [comment]
Yeii :D
